### ISSUE TITLE
GPU无法调用

### ISSUE THREAD

**Issue by maybebao** [zouguojian/RCL-Learning#3]
作者大大您好，我对您的代码很感兴趣，想运行学习一下，遇到了以下问题：
我的环境是：CUDA 10.0+tensorflow-gpu1.13+py3.6 3060的显卡
显卡是可以调用的，但是运行您的代码会报错误：
```
Traceback (most recent call last):
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 304, in <module>
    main()
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 295, in main
    pre_model.evaluate()
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 247, in evaluate
    pre = self.sess.run((self.pres), feed_dict=feed_dict)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=294, n=6, k=3
	 [[node resnet/Conv2D_7 (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py:71) ]]
	 [[node decoder_convlstm/concat (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\multi_convlstm.py:79) ]]
	 Caused by op 'resnet/Conv2D_7', defined at:
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 304, in <module>
    main()
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 290, in main
    pre_model = Model(para)
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 43, in __init__
    self.model()
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 63, in model
    cnn_out = l.cnn(tf.expand_dims(inputs[:, :, :], axis=3))
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py", line 88, in cnn
    residual2 = self.residual_connected(residual1, block2, 1, 1, 3, 6, residual_name='residual2')
  File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py", line 71, in residual_connected
    conv = tf.nn.conv2d(x1, filter, strides=[1, 1, 1, 1], padding='SAME')
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1113, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Blas SGEMM launch failed : m=294, n=6, k=3
	 [[node resnet/Conv2D_7 (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py:71) ]]
	 [[node decoder_convlstm/concat (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\multi_convlstm.py:79) ]]
```
	 之后我又将gpu禁用后**使用cpu**运行您的代码就是可以正常运行的，不知道是我的版本没有装对还是代码这边不支持gpu训练？
由于我的数据比较大，因此cpu环境下感觉运行效果差，还是想正常调用gpu进行训练。
望回答，感激不尽。

**Comment by zouguojian** [comment]
> 作者大大您好，我对您的代码很感兴趣，想运行学习一下，遇到了以下问题： 我的环境是：CUDA 10.0+tensorflow-gpu1.13+py3.6 3060的显卡 显卡是可以调用的，但是运行您的代码会报错误：
> 
> ```
> Traceback (most recent call last):
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 304, in <module>
>     main()
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 295, in main
>     pre_model.evaluate()
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 247, in evaluate
>     pre = self.sess.run((self.pres), feed_dict=feed_dict)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
>     run_metadata_ptr)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
>     run_metadata)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=294, n=6, k=3
> 	 [[node resnet/Conv2D_7 (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py:71) ]]
> 	 [[node decoder_convlstm/concat (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\multi_convlstm.py:79) ]]
> 	 Caused by op 'resnet/Conv2D_7', defined at:
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 304, in <module>
>     main()
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 290, in main
>     pre_model = Model(para)
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 43, in __init__
>     self.model()
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\run_model.py", line 63, in model
>     cnn_out = l.cnn(tf.expand_dims(inputs[:, :, :], axis=3))
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py", line 88, in cnn
>     residual2 = self.residual_connected(residual1, block2, 1, 1, 3, 6, residual_name='residual2')
>   File "F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py", line 71, in residual_connected
>     conv = tf.nn.conv2d(x1, filter, strides=[1, 1, 1, 1], padding='SAME')
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1113, in conv2d
>     data_format=data_format, dilations=dilations, name=name)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "D:\Anaconda3\envs\tensorflow1.13\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InternalError (see above for traceback): Blas SGEMM launch failed : m=294, n=6, k=3
> 	 [[node resnet/Conv2D_7 (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\res_net.py:71) ]]
> 	 [[node decoder_convlstm/concat (defined at F:\mingcode\RCL-Learning-main\RCL-Learning-main\model\multi_convlstm.py:79) ]]
> ```
> 
> ```
>  之后我又将gpu禁用后**使用cpu**运行您的代码就是可以正常运行的，不知道是我的版本没有装对还是代码这边不支持gpu训练？
> ```
> 
> 由于我的数据比较大，因此cpu环境下感觉运行效果差，还是想正常调用gpu进行训练。 望回答，感激不尽。

你要是使用GPU的话，可以直接加一句话就行了呀。当然，我不确定你的环境哈，但是按照以下方法应该没啥问题，可以试试。

tf.reset_default_graph()
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
logs_path = "board"

os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

Good Luck!!!!!

Best,
Guojian
